[build]
  command = "npm ci && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  DISABLE_OPENCOLLECTIVE = "true"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/debug-orders"
  to = "/.netlify/functions/debug-orders"
  status = 200

[[redirects]]
  from = "/api/fix-order-associations"
  to = "/.netlify/functions/fix-order-associations"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/orders/:id"
  to = "/.netlify/functions/orders/[id]"
  status = 200

[[redirects]]
  from = "/api/kitchen/orders"
  to = "/.netlify/functions/kitchen-orders"
  status = 200

[[redirects]]
  from = "/api/orders/*/status"
  to = "/.netlify/functions/orders-status"
  status = 200

[[redirects]]
  from = "/api/tax-settings"
  to = "/.netlify/functions/tax-settings"
  status = 200

[[redirects]]
  from = "/api/tax-categories"
  to = "/.netlify/functions/tax-categories"
  status = 200

[[redirects]]
  from = "/api/pause-services"
  to = "/.netlify/functions/pause-services"
  status = 200

[[redirects]]
  from = "/api/store-hours"
  to = "/.netlify/functions/store-hours"
  status = 200

[[redirects]]
  from = "/api/store-hours/*"
  to = "/.netlify/functions/store-hours"
  status = 200

[[redirects]]
  from = "/api/auth/google/callback"
  to = "/.netlify/functions/auth-google-callback"
  status = 200

[[redirects]]
  from = "/api/auth/google"
  to = "/.netlify/functions/auth-google"
  status = 200

[[redirects]]
  from = "/api/user/profile"
  to = "/.netlify/functions/user-profile"
  status = 200

[[redirects]]
  from = "/api/user/rewards"
  to = "/.netlify/functions/user-rewards"
  status = 200

[[redirects]]
  from = "/api/user/redemptions"
  to = "/.netlify/functions/user-redemptions"
  status = 200

[[redirects]]
  from = "/api/rewards/*/redeem"
  to = "/.netlify/functions/rewards-redeem"
  status = 200

[[redirects]]
  from = "/api/user/vouchers"
  to = "/.netlify/functions/user-vouchers"
  status = 200

[[redirects]]
  from = "/api/vouchers/validate"
  to = "/.netlify/functions/vouchers/validate"
  status = 200

[[redirects]]
  from = "/api/debug-user"
  to = "/.netlify/functions/debug-user"
  status = 200

[[redirects]]
  from = "/api/fix-user-link"
  to = "/.netlify/functions/fix-user-link"
  status = 200

[[redirects]]
  from = "/api/test-auth"
  to = "/.netlify/functions/test-auth"
  status = 200

[[redirects]]
  from = "/api/emergency-fix"
  to = "/.netlify/functions/emergency-fix"
  status = 200

[[redirects]]
  from = "/api/fix-user-migration"
  to = "/.netlify/functions/fix-user-migration"
  status = 200

[[redirects]]
  from = "/api/restore-user-points"
  to = "/.netlify/functions/restore-user-points"
  status = 200

[[redirects]]
  from = "/api/debug-user-orders"
  to = "/.netlify/functions/debug-user-orders"
  status = 200

[[redirects]]
  from = "/api/recover-user-orders"
  to = "/.netlify/functions/recover-user-orders"
  status = 200

[[redirects]]
  from = "/api/debug-orders-schema"
  to = "/.netlify/functions/debug-orders-schema"
  status = 200

[[redirects]]
  from = "/api/redeem-no-auth"
  to = "/.netlify/functions/redeem-no-auth"
  status = 200

[[redirects]]
  from = "/api/run-voucher-migration"
  to = "/.netlify/functions/run-voucher-migration"
  status = 200

[[redirects]]
  from = "/api/debug-vouchers"
  to = "/.netlify/functions/debug-vouchers"
  status = 200

[[redirects]]
  from = "/api/user/active-vouchers"
  to = "/.netlify/functions/user-active-vouchers"
  status = 200

[[redirects]]
  from = "/api/debug-auth"
  to = "/.netlify/functions/debug-auth"
  status = 200

[[redirects]]
  from = "/api/test-auth-simple"
  to = "/.netlify/functions/test-auth-simple"
  status = 200

[[redirects]]
  from = "/api/debug-token-simple"
  to = "/.netlify/functions/debug-token-simple"
  status = 200

[[redirects]]
  from = "/api/menu-items"
  to = "/.netlify/functions/menu-items"
  status = 200

[[redirects]]
  from = "/api/menu-items/*"
  to = "/.netlify/functions/menu-items"
  status = 200

[[redirects]]
  from = "/api/menu/:id"
  to = "/.netlify/functions/menu-item"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev:client"
  port = 8888
  targetPort = 5173
  publish = "dist/public"
  functionsPort = 8889
